### ISSUE TITLE
728x90: Default : File size exceed there.

### ISSUE THREAD

**Issue by bikash-sebpo** [sebpo1/USCS_3153#4]
![Snag_33f4b09](https://github.com/sebpo1/USCS_3153/assets/95098369/8a0bb565-defb-4db6-936d-419cb47a62fc)

**Comment by rubel-sebpo** [comment]
image updated, please check

**Comment by Zeba-SEBPO** [comment]
solved

![image](https://github.com/sebpo1/USCS_3153/assets/142499806/a0132158-2638-4d9e-ad89-059a3a608b10)
